package com.dark.enchantmentprogression.client;

import com.dark.enchantmentprogression.ClientUpgradeEligibility;
import com.dark.enchantmentprogression.ProgressionDisplay;
import com.dark.enchantmentprogression.PendingUpgrade;
import com.dark.enchantmentprogression.UpgradeSession;
import com.dark.enchantmentprogression.network.UpgradeRequest;
import com.dark.enchantmentprogression.network.UpgradeResult;
import net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.input.MouseButtonEvent;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraft.world.item.enchantment.EnchantmentHelper;
import java.util.ArrayList;
import java.util.List;

public final class ProgressionScreen extends Screen {
 private static final int W=410,H=244,RH=27,VISIBLE=5,BG=0xF20A0709,INNER=0xF2160B0E,ROW=0xE3221116,RED=0xFFB51E2D,BRIGHT=0xFFFF3348,GOLD=0xFFE7B45A,TEXT=0xFFF1E4D0,MUTED=0xFF9C8582,GREEN=0xFF72E28A;
 private final Screen parent; private final List<Row> rows=new ArrayList<>(); private final PendingUpgrade pending=new PendingUpgrade(); private final UpgradeSession session=new UpgradeSession();
 private int scroll,refreshTicks,tab; private Row selected,confirm; private Component status=Component.empty(); private int statusColor=MUTED;
 public ProgressionScreen(Screen parent){super(Component.translatable("enchantment_progression.title"));this.parent=parent;}
 @Override protected void init(){super.init();rebuild();addRenderableWidget(Button.builder(Component.translatable("gui.back"),b->onClose()).bounds(width/2-42,Math.min(height-24,top()+H+5),84,20).build());}
 private int left(){return width/2-W/2;} private int top(){return Math.max(10,height/2-H/2-8);}
 private void rebuild(){String sid=selected==null?null:selected.id().toString();rows.clear();Minecraft mc=Minecraft.getInstance();if(mc.player==null||mc.level==null)return;ItemStack stack=mc.player.getMainHandItem();if(stack.isEmpty())return;var stored=EnchantmentHelper.getEnchantmentsForCrafting(stack);var reg=mc.level.registryAccess().lookupOrThrow(Registries.ENCHANTMENT);reg.listElements().forEach(h->{int level=EnchantmentHelper.getItemEnchantmentLevel(h,stack);if(level<=0&&!h.value().isSupportedItem(stack))return;boolean ok=true;for(var e:stored.entrySet())if(e.getIntValue()>0&&!e.getKey().equals(h)&&!Enchantment.areCompatible(e.getKey(),h)){ok=false;break;}Row r=new Row(h,level,ok);if(matches(r))rows.add(r);});rows.sort((a,b)->a.name().getString().compareToIgnoreCase(b.name().getString()));scroll=Math.min(scroll,Math.max(0,rows.size()-VISIBLE));selected=null;if(sid!=null)for(Row r:rows)if(r.id().toString().equals(sid))selected=r;if(selected==null&&!rows.isEmpty())selected=rows.get(0);}
 private boolean matches(Row r){if(tab==0)return true;String s=r.id().toString();boolean def=has(s,"protection","respiration","aqua_affinity","feather_falling","thorns","binding");boolean util=has(s,"efficiency","fortune","silk_touch","unbreaking","mending","luck_of_the_sea","lure","swift_sneak","soul_speed");return tab==1?!def&&!util:tab==2?def:util;} private static boolean has(String s,String...a){for(String x:a)if(s.contains(x))return true;return false;}
 @Override public void extractRenderState(GuiGraphicsExtractor g,int mx,int my,float delta){int l=left(),t=top();g.fill(l-3,t-3,l+W+3,t+H+3,0xEE050305);g.outline(l-3,t-3,W+6,H+6,0xFF4C1119);g.fill(l,t,l+W,t+H,BG);g.outline(l,t,W,H,RED);g.fill(l+5,t+5,l+W-5,t+31,INNER);g.outline(l+5,t+5,W-10,26,0xFF6B1721);g.centeredText(font,Component.literal("✦  ENCHANTMENT PROGRESSION  ✦"),width/2,t+12,BRIGHT);g.text(font,Component.literal("᛫ ᚱ ᛫ ᚾ ᛫ ᛟ ᛫"),l+14,t+35,0xFF6E1C28,false);g.text(font,Component.literal("᛫ ᛟ ᛫ ᚾ ᛫ ᚱ ᛫"),l+W-92,t+35,0xFF6E1C28,false);
 Minecraft mc=Minecraft.getInstance();ItemStack stack=mc.player==null?ItemStack.EMPTY:mc.player.getMainHandItem();g.fill(l+10,t+48,l+112,t+91,0xD00D090B);g.outline(l+10,t+48,102,43,0xFF5D1820);if(!stack.isEmpty())g.fakeItem(stack,l+18,t+60);g.text(font,stack.isEmpty()?Component.translatable("enchantment_progression.no_item"):stack.getHoverName(),l+41,t+57,TEXT,false);if(mc.player!=null)g.text(font,Component.literal("✦ "+mc.player.experienceLevel+" LEVELS"),l+41,t+73,GREEN,false);
 String[] tabs={"ALL","OFFENSE","DEFENSE","UTILITY"};int tx=l+120;for(int i=0;i<4;i++){int x=tx+i*66;g.fill(x,t+51,x+63,t+70,i==tab?0xFF52121C:0xFF211015);g.outline(x,t+51,63,19,i==tab?BRIGHT:0xFF51202A);g.centeredText(font,Component.literal(tabs[i]),x+31,t+57,i==tab?TEXT:MUTED);}
 int y=t+99;for(int i=scroll,n=0;i<rows.size()&&n<VISIBLE;i++,n++,y+=RH){Row r=rows.get(i);ProgressionDisplay d=ProgressionDisplay.forLevel(r.level);boolean afford=mc.player!=null&&(mc.player.getAbilities().instabuild||mc.player.experienceLevel>=d.xpCost());g.fill(l+10,y,l+257,y+23,r==selected?0xEF3A151C:ROW);g.outline(l+10,y,247,23,r==selected?BRIGHT:0xFF4B1A22);g.text(font,r.name(),l+17,y+4,TEXT,false);g.text(font,Component.literal(roman(r.level)+" → "+roman(d.targetLevel())),l+126,y+4,GOLD,false);int c=(!r.compatible||d.capped())?MUTED:(afford?GREEN:0xFFFF6868);g.text(font,Component.literal(d.capped()?"MAX":d.xpCost()+" XP"),l+184,y+4,c,false);g.text(font,Component.literal(d.capped()?"◆":r.compatible?"UP":"LOCK"),l+228,y+4,c,false);}
 int dx=l+265;g.fill(dx,t+99,l+W-10,t+H-17,0xD00D090B);g.outline(dx,t+99,W-275,H-116,0xFF5D1820);if(selected!=null){ProgressionDisplay d=ProgressionDisplay.forLevel(selected.level);g.centeredText(font,selected.name(),dx+67,t+106,TEXT);g.centeredText(font,Component.literal("ENCHANTMENT PATH"),dx+67,t+120,MUTED);int start=Math.max(1,selected.level-1),ny=t+139;for(int n=start;n<start+4;n++){boolean owned=n<=selected.level,next=n==selected.level+1;int nx=dx+11+(n-start)*31;g.fill(nx,ny,nx+23,ny+23,owned?0xFF7A1824:next?0xFF45131B:0xFF171014);g.outline(nx,ny,23,23,owned?BRIGHT:next?GOLD:0xFF4B2830);g.centeredText(font,Component.literal(roman(n)),nx+11,ny+7,owned?TEXT:next?GOLD:MUTED);}g.centeredText(font,Component.literal(d.capped()?"MAXIMUM REACHED":"NEXT: "+roman(d.targetLevel())+" • "+d.xpCost()+" XP"),dx+67,t+170,d.capped()?MUTED:GOLD);g.centeredText(font,Component.literal(selected.compatible?"SELECT ROW TO UPGRADE":"CONFLICT LOCKED"),dx+67,t+187,selected.compatible?MUTED:0xFFFF6868);}
 if(!status.getString().isEmpty())g.centeredText(font,status,width/2,t+H-12,statusColor);if(pending.isPending())g.centeredText(font,Component.literal("✦ CHANNELING ENCHANTMENT… ✦"),width/2,t+84,GOLD);if(confirm!=null)drawConfirm(g,t);super.extractRenderState(g,mx,my,delta);}
 private void drawConfirm(GuiGraphicsExtractor g,int t){int x=width/2-105,y=t+68;ProgressionDisplay d=ProgressionDisplay.forLevel(confirm.level);g.fill(x-2,y-2,x+212,y+91,0xFA050305);g.outline(x-2,y-2,214,93,BRIGHT);g.fill(x+3,y+3,x+207,y+24,0xFF2D0E14);g.centeredText(font,Component.literal("CONFIRM ENCHANTMENT"),width/2,y+9,TEXT);g.centeredText(font,confirm.name(),width/2,y+33,GOLD);g.centeredText(font,Component.literal(roman(confirm.level)+" → "+roman(d.targetLevel())+"   COST: "+d.xpCost()+" XP"),width/2,y+48,TEXT);g.fill(x+14,y+65,x+99,y+83,0xFF4B1119);g.outline(x+14,y+65,85,18,RED);g.centeredText(font,Component.literal("CANCEL"),x+56,y+70,MUTED);g.fill(x+111,y+65,x+196,y+83,0xFF711521);g.outline(x+111,y+65,85,18,BRIGHT);g.centeredText(font,Component.literal("ENCHANT"),x+153,y+70,TEXT);}
 @Override public boolean mouseClicked(MouseButtonEvent c,boolean doubled){double mx=c.x(),my=c.y();int l=left(),t=top();if(confirm!=null){int x=width/2-105,y=t+68;if(my>=y+65&&my<=y+83){if(mx>=x+14&&mx<=x+99){confirm=null;return true;}if(mx>=x+111&&mx<=x+196){Row r=confirm;confirm=null;send(r);return true;}}return true;}int tx=l+120;if(my>=t+51&&my<=t+70)for(int i=0;i<4;i++)if(mx>=tx+i*66&&mx<=tx+i*66+63){tab=i;scroll=0;rebuild();return true;}int y=t+99;for(int i=scroll,n=0;i<rows.size()&&n<VISIBLE;i++,n++,y+=RH){Row r=rows.get(i);if(mx>=l+10&&mx<=l+257&&my>=y&&my<=y+23){selected=r;Minecraft mc=Minecraft.getInstance();boolean creative=mc.player!=null&&mc.player.getAbilities().instabuild;int xp=mc.player==null?0:mc.player.experienceLevel;if(ClientUpgradeEligibility.canRequest(pending.isPending(),r.compatible,creative,r.level,xp))confirm=r;return true;}}return super.mouseClicked(c,doubled);}
 private void send(Row r){Identifier id=r.id();long req=session.begin(id.toString());if(req==0)return;pending.begin();status=Component.empty();if(!ClientPlayNetworking.canSend(UpgradeRequest.TYPE)){session.complete();pending.complete();status=Component.literal("Server does not support Enchantment Progression");statusColor=0xFFFF6868;return;}ClientPlayNetworking.send(new UpgradeRequest(req,id));}
 @Override public boolean mouseScrolled(double x,double y,double h,double v){scroll=Math.max(0,Math.min(Math.max(0,rows.size()-VISIBLE),scroll+(v<0?1:-1)));return true;}
 public void acceptResult(UpgradeResult r){if(!session.accepts(r.requestId(),r.enchantmentId().toString()))return;session.complete();pending.complete();if(r.success()){status=Component.literal("✦ UPGRADE COMPLETE • LEVEL "+r.newLevel()+" ✦");statusColor=GREEN;}else{status=Component.literal("Upgrade rejected: "+r.reason().replace('_',' '));statusColor=0xFFFF6868;}rebuild();}
 @Override public void tick(){super.tick();if(++refreshTicks>=10){refreshTicks=0;rebuild();}if(pending.tick()){session.complete();status=Component.literal("Upgrade timed out — no confirmation received");statusColor=0xFFFF6868;rebuild();}}
 @Override public void onClose(){Minecraft.getInstance().gui.setScreen(parent);}@Override public boolean isPauseScreen(){return false;}
 private record Row(Holder.Reference<Enchantment> holder,int level,boolean compatible){Component name(){return holder.value().description().copy();}Identifier id(){return holder.unwrapKey().orElseThrow().identifier();}}
 private static String roman(int n){if(n<=0)return"—";if(n>20)return Integer.toString(n);int[]v={10,9,5,4,1};String[]s={"X","IX","V","IV","I"};StringBuilder b=new StringBuilder();for(int i=0;i<v.length;i++)while(n>=v[i]){b.append(s[i]);n-=v[i];}return b.toString();}
}
